# Generated by Django 4.0.3 on 2022-04-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nome')),
                ('quantity', models.FloatField(verbose_name='quantidade')),
                ('proteins', models.FloatField(verbose_name='proteínas')),
                ('carbohydrates', models.FloatField(verbose_name='carboidratos')),
                ('fats', models.FloatField(verbose_name='gorduras')),
            ],
            options={
                'db_table': 'food',
            },
        ),
    ]
